-- AlterTable
ALTER TABLE "Sample" ADD COLUMN     "hasMidi" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "hasStems" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "hasWav" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "midiPrice" DOUBLE PRECISION,
ADD COLUMN     "stemsPrice" DOUBLE PRECISION,
ADD COLUMN     "wavPrice" DOUBLE PRECISION;
